---
all:
  children:
    iaas_1:
      hosts: 
        opensuse:
          include_vars: ./host_vars/opensuse.yml

    iaas_2:
      hosts: 
        clearos:
          include_vars: ./host_vars/clearos.yml

    iaas_3:
      hosts: 
        alpine:
          include_vars: ./host_vars/alpine.yml

    iaas_4:
      hosts: 
        fedora:
          include_vars: ./host_vars/fedora.yml

