---
apiVersion: v1
kind: Pod
metadata:
  name: app
  namespace: glbasecamp
  labels: 
    app: glbasecamp
    run: glbasecamp
spec:
  containers:
    - image: iamnotaskynet/gl_basecamp_test:0.4.1
      name: app
      ports:
        - containerPort: 8000
          name: http